POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title"   : "Great Blog of Awesome",
  "author"  : "Master Creator Duke",
  "url"     : "http://fakeurl.gov",
  "likes"   : 0
}